### ISSUE TITLE
alt key presses are emulated incorrectly

### ISSUE THREAD

**Issue by connorjclark** [NewCreature/Allegro-Legacy#27]
According to the allegro 4 [docs](https://www.allegro.cc/manual/4/api/keyboard-routines/readkey#:~:text=Pressing%20alt%2Bkey%20returns%20only%20the%20scancode%2C%20with%20a%20zero%20ASCII%20code%20in%20the%20low%20byte), key values for alt+key presses should have the keycode portion of the byte set to 0. GUI code depends on this value being 0 to detect an ALT key press and do shortcuts (see [`menu_alt_key`](https://github.com/liballeg/allegro5/blob/8a386b2754608b66d46f10abf993abf8ab16902d/src/gui.c#L1709)  and [`update_dialog`](https://github.com/liballeg/allegro5/blob/8a386b2754608b66d46f10abf993abf8ab16902d/src/gui.c#L1264)).

**Comment by NewCreature** [comment]
Allegro Legacy passes keyboard input into `_handle_key_press()`.  I see some potential issues with the current implementation. Currently, all key presses that are not in the modifier range will report key presses with the key code set to 0. Does this imply that every key press is interpreted by Allegro Legacy's keyboard implementation as Alt+key presses?

Allegro Legacy also handles Allegro's `ALLEGRO_EVENT_KEY_CHAR`. This event gives a key code and a scan code to `_handle_key_press()`. I'll have to test this out, but I'm thinking Alt+key might not generate an `ALLEGRO_EVENT_KEY_CHAR`. On MacOS I get `å` from Alt+A. I'll have to play around with this to see what needs to be done here.

**Comment by connorjclark** [comment]
Oops, I forgot to share the solution that worked for my project: https://github.com/ArmageddonGames/ZeldaClassic/pull/784/files

Just checking if the ALT modifier is set for `ALLEGRO_EVENT_KEY_CHAR` and if so, pass a 0 as the keycode. I confirmed this resolved the issue I saw wrt. the GUI ALT shortcuts on mac and windows.

**Comment by connorjclark** [comment]
There's also `key_shifts`, which is nearly a 1:1 mapping with a5 modifiers value on the keyboard event. I think the only difference is that `ALTGR` exists now but didn't for a4. see https://github.com/ArmageddonGames/ZeldaClassic/commit/7240fae04e4ceb2040a0bfa2eecb46190f4124e5

**Comment by NewCreature** [comment]
Seems like your fix will work. I was worried about missing Unicode input, but I don't think Allegro 4 actually accepts Unicode input anyway, just ASCII. Your fix should make the keyboard input match how it worked in Allegro 4, which is mainly what we're trying to accomplish here. If you want to do a PR, I'll accept it. Otherwise, I'll implement this fix myself soon.

**Comment by connorjclark** [comment]
Cool, I'll send over a couple PRs this evening.
