### ISSUE TITLE
Loops in midi playback result in timer thread deadlock

### ISSUE THREAD

**Issue by connorjclark** [NewCreature/Allegro-Legacy#29]
Play a looped midi with loop_start >= 1 to see that, when the loop_end is reached the MIDI trails off and never starts again.

This is due to how midi.c creates a timer `midi_player` that itself calls `remove_int(midi_player)`, resulting in a5_timer.c attempting to destroy the thread (the same thread that is calling this function), which result in an attempt to `join` itself, resuling in a deadlock.

A fix I went with, and confirms working so far, was to create a timer/thread pool and just stop timers when no longer needed, keeping the thread around for future timers. See https://github.com/ArmageddonGames/ZeldaClassic/commit/8cee72e4393d2a761e36ee20c621244142194c4c#diff-91f4de1cced2e908f3642fd00cf43250f4dcf52381ef8bee96e7bc84fef40a43

A couple other issues I found (and fixed in commit above):

- need to use the `param` value when checking if a timer_data already exists, _in addition_ to the `timer_param_proc`. See a4 [`find_param_timer_slot`](https://github.com/liballeg/allegro5/blob/8a386b2754608b66d46f10abf993abf8ab16902d/src/timer.c#L275)
- a5_timer does not attempt to update an existing matching timer if there happens to be already at max, even though it could still do an update w/o going over the limit. see https://github.com/NewCreature/Allegro-Legacy/blob/3aa6280623d8c9e64ab6ed0341c988853f1b7c96/src/a5/a5_timer.c#L130-L139
- doesn't update a timer `param` https://github.com/NewCreature/Allegro-Legacy/blob/3aa6280623d8c9e64ab6ed0341c988853f1b7c96/src/a5/a5_timer.c#L191-L192}

If this approach sounds good, lmk and I'll send a PR.

**Comment by NewCreature** [comment]
Looks good. If you send a PR with the changes I'll accept it.
