### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by NewCreature** [NewCreature/Allegro-Legacy#4]
We need to make a README to describe what this library is and what additional functionality it provides that is not described in the included A4 documentation.

**Comment by ZoriaRPG** [comment]
I requested this by PM on allegro.cc.

Docs on usage, how to bind to ag4 static libs; how it should be compiled to link into ag4.4x, and so forth.

I find it unclear, as the entirety of ag44, and ag5 aren't part of this package, so I presume that both of those are required, and somehow this is all compiled together?

**Comment by NewCreature** [comment]
I replied to your message on a.cc. You can read about all of this on there. Basically, Allegro Legacy will do what you need when it is finished.

MIDI support will be handled through a separate library (code will be included as part of Allegro Legacy). I wanted that code to not be tied specifically to Allegro Legacy since I needed it for other projects. Using a separate API also means reducing maintenance requirements on the main Allegro Legacy code. Ultimately, your Allegro 4 MIDI code will work just fine using Allegro Legacy once I get this implemented.

Regarding DIGMID, I'll have to look into it. I'm not sure how that is implemented, but it probably just uses the digital sound routines. Those things are already being routed through Allegro 5's audio add-on so it shouldn't be too difficult to enable DIGMID support as well.
